# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: COINSE
email: shin.yoo [at] kaist.ac.kr
description: # this means to ignore newlines until "baseurl:"
    COINSE Lab,<br/>
    <a href='http://cs.kaist.ac.kr'>School of Computing</a>,<br/>
    <a href='http://www.kaist.ac.kr'>Korea Advanced Institute of Science and Technology</a>,<br/>
    291 Daehak Ro, Yuseong Gu,<br/>
    Daejeon, 34141,<br/>
    Republic of Korea
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://coinse.kaist.ac.kr" # the base hostname & protocol for your site
twitter_username: coinselab
github_username: coinse
# wiki_username: coinse wiki (internal)
bitbucket_username: teamcoinse

plugins: ["jekyll-twitter-plugin"]

# Build settings
markdown: kramdown

scholar:
    style: ./_bibtex/coinse-csl.csl
    source: ./_bibtex
    bibliography: coinse.bib
    bibliography_template: coinse_bib_template
    repository: ./publications/pdfs
    sort_by: year,month
    order: descending
